### ISSUE TITLE
Some Facebook user profile links are not reachable

### ISSUE THREAD

**Issue by tdg** [swapmyvote/swapmyvote#281]
> I seem to have successfully arranged a vote swap, but the link provided to my swap partner's Facebook is not working.
> 
> I get a 'Sorry, this content is not available' message.
> 
> This is the link:
> https://www.facebook.com/app_scoped_user_id/YXNpZADpBWEd1aXIwTktvOHN4aVVYcW1laFhOU0p1NmZAnQTlfMmMyYTNRTHRYQ2Q0RDFwN1MzMVFycFZAROW92UWE4OHRaNE44WGdYd05rYXRtSGxOS2pBcVYwQlpDQlYxbzRGMGdwUW5waDI5SgZDZD/
> 
> Apologies if you're already aware of this issue.

## Potential actions

- [x] Grab a load of profile links from prod db and test them to get a sense of scale of problem
- [x] ~~Reach out to Facebook support~~ Waste of time
- [x] Update copy to warn that the link might not work
- [x] Allow users to consent to having their email address shared with their partner as per #102 (this is a good idea anyway)
- [x] write to all confirmed swap partners registered via Facebook (#298)
- [x] update swap confirmation page with better text (done in 68a54f1db35f16b60a9603bfe8d4e73d8a9cfbcb)
- [x] update  swap confirmation **email** with better text (#346)
- [x] facebook profile link - backlogged swaps decisions #336
- [x] allow swappers to retrospectively consent to sharing email #337

**Comment by baob** [comment]
I suspect the first part of the path may hint at the problem ... the url is only usable for authenticated users of the 'app' ? The facebook app ? do we need to save a token somewhere ?

**Comment by aspiers** [comment]
Yes that's by design and omniauth saves the token.

**Comment by baob** [comment]
So thinking about other users viewing that path ... that path will then only be usable by some other users who has authenticated to our 'app' ?

**Comment by aspiers** [comment]
It will only be viewable by people logged into the app and then it
redirects to the normal url.

**Comment by baob** [comment]
Okay so, it sounds like this issue is well understood, and no further action is needed other than that already identified in #298 . 

If I've understood right and that's the case, can we either close this, or mark blocked or in some other way indicate that no further work is necessary ?

**Comment by tdg** [comment]
I don't fully understand - can we fix this? If so, let's do #298 after. If not, we need to find another strategy entirely to keep these users in the system - for which we should have another Issue.

**Comment by aspiers** [comment]
It's not well understood unfortunately.  I don't why this is happening, and I have no idea how to fix it.  My best guess is it's related to privacy settings, but the only options I can think of are:

1. gather a much larger dataset (i.e. experiment a lot more and/or ask testers to report their experiences) to try to figure out if there's a pattern
2. ask Facebook for help and pray for a response

**Comment by baob** [comment]
https://github.com/swapmyvote/swapmyvote/issues/298#issuecomment-562923627

**Comment by tdg** [comment]
Can we warn the user that we need the timeline permission, and what will happen without (they might find it hard to get a swap). Reassure them nothing is shared with Facebook etc

**Comment by tdg** [comment]
We could also email users who fall into this category with a system message calling for action #306

**Comment by aspiers** [comment]
The problem is how to determine which users fall into this category - short of manual testing I can't think of any easy way.

**Comment by aspiers** [comment]
Looks like we're SoL on this:

- https://stackoverflow.com/questions/52850222/url-from-user-link-permission-get-error
- https://stackoverflow.com/questions/54488354/fb-user-link-permission-is-it-possible-to-get-a-link-even-with-limited-validit
- https://stackoverflow.com/questions/51658999/issue-while-opening-user-facebook-page-by-user-link
- https://developers.facebook.com/blog/post/2018/05/01/facebook-login-updates-further-protect-privacy/?hc_location=ufi says:
> For most apps, links will only redirect to the individual's Facebook profile for logged in people in the person's extended network. Soon, other logged in people will be able to invite the person referred to by the link to connect with them on the Facebook platform.

We currently have twice as many fb users as Twitter.

**Comment by baob** [comment]
Here’s an idea … that definitely will need refinement …. but how about we create a ‘swap lounge’ group on FB …. the idea is that if you’ve not confirmed your swap, you join the lounge, and there you can find your swapper and become FB friends … then you leave the lounge

The problem with it is we have 1030 unconfirmed swaps right now, so people will need to be prepared to search within the lounge.

**Comment by baob** [comment]
> * [ ]  Allow users to consent to having their email address shared with their partner as per #102 (this is a good idea anyway)

As of commit 57cd4ffa (email login branch) this consent is implicit in email login, but not not clear for facebook or twitter login

**Comment by aspiers** [comment]
DONE!!!
