### ISSUE TITLE
GDPR compliance

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#66]
GDPR came in since GE2017 so we need to make sure we're compliant.  Let's use this issue to track [all sub-tasks needed for compliance](https://github.com/swapmyvote/swapmyvote/labels/GDPR).

- [x] ask consent for cookies (#65)
- [x] establish way for users to be forgotten (#67)
- [x] establish data controller (#68)
- [ ] Clarify in privacy policy what info is shared from Facebook & Twitter to SMV (email, name) (#73)
- [x] establish informed consent at point of data entry (login, confirm email address, confirm mobile phone (#74)
- [ ] anonymise IPs (#101)
- [ ] beef up privacy policy (#73)

**Comment by aspiers** [comment]
@tdg Did I miss anything?

**Comment by tdg** [comment]
@aspiers updated with a few more things and cross referenced to new issues

**Comment by egglestn** [comment]
Here's a link to a privacy policy template generator, might be useful: https://www.freeprivacypolicy.com/blog/gdpr-privacy-policy/

**Comment by tdg** [comment]
@georgecrawford would you like to have a look at how we can present this information in the UX

**Comment by egglestn** [comment]
Do we need to mention anything about how long we store data for? Do we do cleanup all DB tables at some point after the election?

**Comment by tdg** [comment]
> Do we need to mention anything about how long we store data for? Do we do cleanup all DB tables at some point after the election?

Yes I've been thinking about this too. I think we should commit to anonymising all data (removing name, email, and social information) from our tables and delete from records within eight weeks of the election result, or similar. Does this sound about right to you, too, @aspiers? 

It would mean that we can still analyse and discuss political impact of the platform at the election.

We would keep names and contact information (where opted in) in the Mailchimp list(s).

**Comment by aspiers** [comment]
Sounds good to me!

**Comment by aspiers** [comment]
We can just use https://github.com/swapmyvote/swapmyvote/labels/GDPR to track all GDPR issues, so closing this.
