### ISSUE TITLE
GE2024 launch checklist

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#842]
Copied from #655 (which is the issue about having a good checklist ready for any election) for use specifically with GE2024.  Ideally most of these should be filed as separate issues (if they haven't already).  See also [the project](https://github.com/orgs/swapmyvote/projects/2/views/3?sliceBy%5Bvalue%5D=00+GE2024+M2%3A+ready+to+open+to+general+public).

## L1

We will want to be prepared before the election is called (or inevitable to be so) with:

- [ ] a reasonable, early and realistic, timeframe by which the platform can be live for swapping as per L2 below
- [x] copy for the 'closed-warm-up' state
- [x] email / data capture for interested users via ActionNetwork during closed warm up mode
- [ ] suitable 'announcement' comms across channels
- [ ] template testing regime and schedule in place
- **PLEASE ADD/EDIT THIS LIST**

## L2

In order to taking the platform live we will need:

- [x] up to date data files (see info in Pull Request #658 )
- [x] suitable server capacity
- [x] update of any parts of the stack required for security updates (e.g. Rails, Ruby, Heroku, Node.js)
- [x] adequate testing to have taken place
- [x] suitable announcement comms across channels
- [x] plan for further campaign comms

**Comment by tdg** [comment]
I think 
> data capture for interested users
Is the current closed state action network mailing list form currently live

**Comment by tdg** [comment]
> suitable announcement comms across channels
>plan for further campaign comms
There are in progress

**Comment by aspiers** [comment]
We're live, so closing.
